site_name: springable
theme:
    name: material
    language: en
    direction: ltr
    palette:
        primary: deep-purple
        accent: green
    features:
      - content.code.copy
      - content.tabs.link
    icon:
        repo: fontawesome/brands/github
    favicon: favicon.png
    logo: favicon.png
    font:
      text: Roboto Serif
      code: JetBrains Mono
repo_url: https://github.com/ducarme/springable
repo_name: See code on Github
nav:
  - index.md
  - getting_started.md
  - many_examples.md
  - creating_the_spring_model_csv_file.md
  - specifying_a_nonlinear_mechanical_behavior.md
  - configuring_simulation_settings.md
  - advanced_topics.md
  - about_and_contact.md
# - all_assets.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.blocks.caption:
      prepend: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

